name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md"]

# We are using OpenID Connect to authenticate with Azure with secret.
# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: [self-hosted, idp]
    steps:
      - uses: actions/checkout@v4
      - run: ./test.ps1
        shell: pwsh
        
  linearb:
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: release
    secrets: inherit










